// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// bkp_posterior_update_rcpp
List bkp_posterior_update_rcpp(const arma::mat& K, const arma::vec& y, const arma::vec& m, const arma::vec& alpha0, const arma::vec& beta0);
RcppExport SEXP _BKP_bkp_posterior_update_rcpp(SEXP KSEXP, SEXP ySEXP, SEXP mSEXP, SEXP alpha0SEXP, SEXP beta0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type K(KSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type m(mSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type alpha0(alpha0SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type beta0(beta0SEXP);
    rcpp_result_gen = Rcpp::wrap(bkp_posterior_update_rcpp(K, y, m, alpha0, beta0));
    return rcpp_result_gen;
END_RCPP
}
// dkp_posterior_update_rcpp
List dkp_posterior_update_rcpp(const arma::mat& K, const arma::mat& Y, const arma::mat& alpha0);
RcppExport SEXP _BKP_dkp_posterior_update_rcpp(SEXP KSEXP, SEXP YSEXP, SEXP alpha0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type K(KSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type alpha0(alpha0SEXP);
    rcpp_result_gen = Rcpp::wrap(dkp_posterior_update_rcpp(K, Y, alpha0));
    return rcpp_result_gen;
END_RCPP
}
// get_prior_bkp_noninformative_rcpp
List get_prior_bkp_noninformative_rcpp(int n);
RcppExport SEXP _BKP_get_prior_bkp_noninformative_rcpp(SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(get_prior_bkp_noninformative_rcpp(n));
    return rcpp_result_gen;
END_RCPP
}
// get_prior_bkp_fixed_rcpp
List get_prior_bkp_fixed_rcpp(int n, double r0, double p0);
RcppExport SEXP _BKP_get_prior_bkp_fixed_rcpp(SEXP nSEXP, SEXP r0SEXP, SEXP p0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type r0(r0SEXP);
    Rcpp::traits::input_parameter< double >::type p0(p0SEXP);
    rcpp_result_gen = Rcpp::wrap(get_prior_bkp_fixed_rcpp(n, r0, p0));
    return rcpp_result_gen;
END_RCPP
}
// get_prior_bkp_adaptive_rcpp
List get_prior_bkp_adaptive_rcpp(const arma::mat& K, const arma::vec& y, const arma::vec& m, double r0);
RcppExport SEXP _BKP_get_prior_bkp_adaptive_rcpp(SEXP KSEXP, SEXP ySEXP, SEXP mSEXP, SEXP r0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type K(KSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type m(mSEXP);
    Rcpp::traits::input_parameter< double >::type r0(r0SEXP);
    rcpp_result_gen = Rcpp::wrap(get_prior_bkp_adaptive_rcpp(K, y, m, r0));
    return rcpp_result_gen;
END_RCPP
}
// get_prior_dkp_noninformative_rcpp
arma::mat get_prior_dkp_noninformative_rcpp(int n, int q);
RcppExport SEXP _BKP_get_prior_dkp_noninformative_rcpp(SEXP nSEXP, SEXP qSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type q(qSEXP);
    rcpp_result_gen = Rcpp::wrap(get_prior_dkp_noninformative_rcpp(n, q));
    return rcpp_result_gen;
END_RCPP
}
// get_prior_dkp_fixed_rcpp
arma::mat get_prior_dkp_fixed_rcpp(int n, double r0, const arma::vec& p0);
RcppExport SEXP _BKP_get_prior_dkp_fixed_rcpp(SEXP nSEXP, SEXP r0SEXP, SEXP p0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type r0(r0SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type p0(p0SEXP);
    rcpp_result_gen = Rcpp::wrap(get_prior_dkp_fixed_rcpp(n, r0, p0));
    return rcpp_result_gen;
END_RCPP
}
// get_prior_dkp_adaptive_rcpp
arma::mat get_prior_dkp_adaptive_rcpp(const arma::mat& K, const arma::mat& Y, double r0);
RcppExport SEXP _BKP_get_prior_dkp_adaptive_rcpp(SEXP KSEXP, SEXP YSEXP, SEXP r0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type K(KSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< double >::type r0(r0SEXP);
    rcpp_result_gen = Rcpp::wrap(get_prior_dkp_adaptive_rcpp(K, Y, r0));
    return rcpp_result_gen;
END_RCPP
}
// get_knnx_nanoflann_rcpp
List get_knnx_nanoflann_rcpp(NumericMatrix data, NumericMatrix query, int k);
RcppExport SEXP _BKP_get_knnx_nanoflann_rcpp(SEXP dataSEXP, SEXP querySEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type data(dataSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type query(querySEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(get_knnx_nanoflann_rcpp(data, query, k));
    return rcpp_result_gen;
END_RCPP
}
// kernel_matrix_rcpp
arma::mat kernel_matrix_rcpp(SEXP X, SEXP Xprime, NumericVector theta, std::string kernel, bool isotropic);
RcppExport SEXP _BKP_kernel_matrix_rcpp(SEXP XSEXP, SEXP XprimeSEXP, SEXP thetaSEXP, SEXP kernelSEXP, SEXP isotropicSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type X(XSEXP);
    Rcpp::traits::input_parameter< SEXP >::type Xprime(XprimeSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< std::string >::type kernel(kernelSEXP);
    Rcpp::traits::input_parameter< bool >::type isotropic(isotropicSEXP);
    rcpp_result_gen = Rcpp::wrap(kernel_matrix_rcpp(X, Xprime, theta, kernel, isotropic));
    return rcpp_result_gen;
END_RCPP
}
// loss_fun_brier_bkp_rcpp
double loss_fun_brier_bkp_rcpp(const arma::mat& K, const arma::vec& y, const arma::vec& m, const arma::vec& alpha0, const arma::vec& beta0);
RcppExport SEXP _BKP_loss_fun_brier_bkp_rcpp(SEXP KSEXP, SEXP ySEXP, SEXP mSEXP, SEXP alpha0SEXP, SEXP beta0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type K(KSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type m(mSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type alpha0(alpha0SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type beta0(beta0SEXP);
    rcpp_result_gen = Rcpp::wrap(loss_fun_brier_bkp_rcpp(K, y, m, alpha0, beta0));
    return rcpp_result_gen;
END_RCPP
}
// loss_fun_logloss_bkp_rcpp
double loss_fun_logloss_bkp_rcpp(const arma::mat& K, const arma::vec& y, const arma::vec& m, const arma::vec& alpha0, const arma::vec& beta0);
RcppExport SEXP _BKP_loss_fun_logloss_bkp_rcpp(SEXP KSEXP, SEXP ySEXP, SEXP mSEXP, SEXP alpha0SEXP, SEXP beta0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type K(KSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type m(mSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type alpha0(alpha0SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type beta0(beta0SEXP);
    rcpp_result_gen = Rcpp::wrap(loss_fun_logloss_bkp_rcpp(K, y, m, alpha0, beta0));
    return rcpp_result_gen;
END_RCPP
}
// loss_fun_brier_dkp_rcpp
double loss_fun_brier_dkp_rcpp(const arma::mat& K, const arma::mat& Y, const arma::mat& alpha0);
RcppExport SEXP _BKP_loss_fun_brier_dkp_rcpp(SEXP KSEXP, SEXP YSEXP, SEXP alpha0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type K(KSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type alpha0(alpha0SEXP);
    rcpp_result_gen = Rcpp::wrap(loss_fun_brier_dkp_rcpp(K, Y, alpha0));
    return rcpp_result_gen;
END_RCPP
}
// loss_fun_logloss_dkp_rcpp
double loss_fun_logloss_dkp_rcpp(const arma::mat& K, const arma::mat& Y, const arma::mat& alpha0);
RcppExport SEXP _BKP_loss_fun_logloss_dkp_rcpp(SEXP KSEXP, SEXP YSEXP, SEXP alpha0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type K(KSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type alpha0(alpha0SEXP);
    rcpp_result_gen = Rcpp::wrap(loss_fun_logloss_dkp_rcpp(K, Y, alpha0));
    return rcpp_result_gen;
END_RCPP
}
// optimize_bkp_theta_rcpp
Rcpp::List optimize_bkp_theta_rcpp(const arma::mat& Xnorm, const arma::vec& y, const arma::vec& m, const std::string& prior, const double r0, const double p0, const std::string& loss, const std::string& kernel, const bool isotropic, const int n_grid, const int n_starts, const int max_iter, const double g_lower, const double g_upper);
RcppExport SEXP _BKP_optimize_bkp_theta_rcpp(SEXP XnormSEXP, SEXP ySEXP, SEXP mSEXP, SEXP priorSEXP, SEXP r0SEXP, SEXP p0SEXP, SEXP lossSEXP, SEXP kernelSEXP, SEXP isotropicSEXP, SEXP n_gridSEXP, SEXP n_startsSEXP, SEXP max_iterSEXP, SEXP g_lowerSEXP, SEXP g_upperSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Xnorm(XnormSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type m(mSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type prior(priorSEXP);
    Rcpp::traits::input_parameter< const double >::type r0(r0SEXP);
    Rcpp::traits::input_parameter< const double >::type p0(p0SEXP);
    Rcpp::traits::input_parameter< const std::string& >::type loss(lossSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type kernel(kernelSEXP);
    Rcpp::traits::input_parameter< const bool >::type isotropic(isotropicSEXP);
    Rcpp::traits::input_parameter< const int >::type n_grid(n_gridSEXP);
    Rcpp::traits::input_parameter< const int >::type n_starts(n_startsSEXP);
    Rcpp::traits::input_parameter< const int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< const double >::type g_lower(g_lowerSEXP);
    Rcpp::traits::input_parameter< const double >::type g_upper(g_upperSEXP);
    rcpp_result_gen = Rcpp::wrap(optimize_bkp_theta_rcpp(Xnorm, y, m, prior, r0, p0, loss, kernel, isotropic, n_grid, n_starts, max_iter, g_lower, g_upper));
    return rcpp_result_gen;
END_RCPP
}
// predict_bkp_rcpp
List predict_bkp_rcpp(const arma::mat& K, const arma::vec& alpha0, const arma::vec& beta0, const arma::vec& y, const arma::vec& m);
RcppExport SEXP _BKP_predict_bkp_rcpp(SEXP KSEXP, SEXP alpha0SEXP, SEXP beta0SEXP, SEXP ySEXP, SEXP mSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type K(KSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type alpha0(alpha0SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type beta0(beta0SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type m(mSEXP);
    rcpp_result_gen = Rcpp::wrap(predict_bkp_rcpp(K, alpha0, beta0, y, m));
    return rcpp_result_gen;
END_RCPP
}
// predict_dkp_rcpp
List predict_dkp_rcpp(const arma::mat& K, const arma::mat& alpha0, const arma::mat& Y);
RcppExport SEXP _BKP_predict_dkp_rcpp(SEXP KSEXP, SEXP alpha0SEXP, SEXP YSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type K(KSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type alpha0(alpha0SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Y(YSEXP);
    rcpp_result_gen = Rcpp::wrap(predict_dkp_rcpp(K, alpha0, Y));
    return rcpp_result_gen;
END_RCPP
}
// get_twin_indices_rcpp
List get_twin_indices_rcpp(NumericMatrix data, int g, Nullable<int> v, int runs, int seed);
RcppExport SEXP _BKP_get_twin_indices_rcpp(SEXP dataSEXP, SEXP gSEXP, SEXP vSEXP, SEXP runsSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type data(dataSEXP);
    Rcpp::traits::input_parameter< int >::type g(gSEXP);
    Rcpp::traits::input_parameter< Nullable<int> >::type v(vSEXP);
    Rcpp::traits::input_parameter< int >::type runs(runsSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(get_twin_indices_rcpp(data, g, v, runs, seed));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_BKP_bkp_posterior_update_rcpp", (DL_FUNC) &_BKP_bkp_posterior_update_rcpp, 5},
    {"_BKP_dkp_posterior_update_rcpp", (DL_FUNC) &_BKP_dkp_posterior_update_rcpp, 3},
    {"_BKP_get_prior_bkp_noninformative_rcpp", (DL_FUNC) &_BKP_get_prior_bkp_noninformative_rcpp, 1},
    {"_BKP_get_prior_bkp_fixed_rcpp", (DL_FUNC) &_BKP_get_prior_bkp_fixed_rcpp, 3},
    {"_BKP_get_prior_bkp_adaptive_rcpp", (DL_FUNC) &_BKP_get_prior_bkp_adaptive_rcpp, 4},
    {"_BKP_get_prior_dkp_noninformative_rcpp", (DL_FUNC) &_BKP_get_prior_dkp_noninformative_rcpp, 2},
    {"_BKP_get_prior_dkp_fixed_rcpp", (DL_FUNC) &_BKP_get_prior_dkp_fixed_rcpp, 3},
    {"_BKP_get_prior_dkp_adaptive_rcpp", (DL_FUNC) &_BKP_get_prior_dkp_adaptive_rcpp, 3},
    {"_BKP_get_knnx_nanoflann_rcpp", (DL_FUNC) &_BKP_get_knnx_nanoflann_rcpp, 3},
    {"_BKP_kernel_matrix_rcpp", (DL_FUNC) &_BKP_kernel_matrix_rcpp, 5},
    {"_BKP_loss_fun_brier_bkp_rcpp", (DL_FUNC) &_BKP_loss_fun_brier_bkp_rcpp, 5},
    {"_BKP_loss_fun_logloss_bkp_rcpp", (DL_FUNC) &_BKP_loss_fun_logloss_bkp_rcpp, 5},
    {"_BKP_loss_fun_brier_dkp_rcpp", (DL_FUNC) &_BKP_loss_fun_brier_dkp_rcpp, 3},
    {"_BKP_loss_fun_logloss_dkp_rcpp", (DL_FUNC) &_BKP_loss_fun_logloss_dkp_rcpp, 3},
    {"_BKP_optimize_bkp_theta_rcpp", (DL_FUNC) &_BKP_optimize_bkp_theta_rcpp, 14},
    {"_BKP_predict_bkp_rcpp", (DL_FUNC) &_BKP_predict_bkp_rcpp, 5},
    {"_BKP_predict_dkp_rcpp", (DL_FUNC) &_BKP_predict_dkp_rcpp, 3},
    {"_BKP_get_twin_indices_rcpp", (DL_FUNC) &_BKP_get_twin_indices_rcpp, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_BKP(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
