# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

bkp_posterior_update_rcpp <- function(K, y, m, alpha0, beta0) {
    .Call(`_BKP_bkp_posterior_update_rcpp`, K, y, m, alpha0, beta0)
}

dkp_posterior_update_rcpp <- function(K, Y, alpha0) {
    .Call(`_BKP_dkp_posterior_update_rcpp`, K, Y, alpha0)
}

get_prior_bkp_noninformative_rcpp <- function(n) {
    .Call(`_BKP_get_prior_bkp_noninformative_rcpp`, n)
}

get_prior_bkp_fixed_rcpp <- function(n, r0, p0) {
    .Call(`_BKP_get_prior_bkp_fixed_rcpp`, n, r0, p0)
}

get_prior_bkp_adaptive_rcpp <- function(K, y, m, r0) {
    .Call(`_BKP_get_prior_bkp_adaptive_rcpp`, K, y, m, r0)
}

get_prior_dkp_noninformative_rcpp <- function(n, q) {
    .Call(`_BKP_get_prior_dkp_noninformative_rcpp`, n, q)
}

get_prior_dkp_fixed_rcpp <- function(n, r0, p0) {
    .Call(`_BKP_get_prior_dkp_fixed_rcpp`, n, r0, p0)
}

get_prior_dkp_adaptive_rcpp <- function(K, Y, r0) {
    .Call(`_BKP_get_prior_dkp_adaptive_rcpp`, K, Y, r0)
}

get_knnx_nanoflann_rcpp <- function(data, query, k) {
    .Call(`_BKP_get_knnx_nanoflann_rcpp`, data, query, k)
}

kernel_matrix_rcpp <- function(X, Xprime = NULL, theta = as.numeric( c(0.1)), kernel = "gaussian", isotropic = TRUE) {
    .Call(`_BKP_kernel_matrix_rcpp`, X, Xprime, theta, kernel, isotropic)
}

loss_fun_brier_bkp_rcpp <- function(K, y, m, alpha0, beta0) {
    .Call(`_BKP_loss_fun_brier_bkp_rcpp`, K, y, m, alpha0, beta0)
}

loss_fun_logloss_bkp_rcpp <- function(K, y, m, alpha0, beta0) {
    .Call(`_BKP_loss_fun_logloss_bkp_rcpp`, K, y, m, alpha0, beta0)
}

loss_fun_brier_dkp_rcpp <- function(K, Y, alpha0) {
    .Call(`_BKP_loss_fun_brier_dkp_rcpp`, K, Y, alpha0)
}

loss_fun_logloss_dkp_rcpp <- function(K, Y, alpha0) {
    .Call(`_BKP_loss_fun_logloss_dkp_rcpp`, K, Y, alpha0)
}

optimize_bkp_theta_rcpp <- function(Xnorm, y, m, prior, r0, p0, loss, kernel, isotropic, n_grid, n_starts, max_iter, g_lower, g_upper) {
    .Call(`_BKP_optimize_bkp_theta_rcpp`, Xnorm, y, m, prior, r0, p0, loss, kernel, isotropic, n_grid, n_starts, max_iter, g_lower, g_upper)
}

predict_bkp_rcpp <- function(K, alpha0, beta0, y, m) {
    .Call(`_BKP_predict_bkp_rcpp`, K, alpha0, beta0, y, m)
}

predict_dkp_rcpp <- function(K, alpha0, Y) {
    .Call(`_BKP_predict_dkp_rcpp`, K, alpha0, Y)
}

get_twin_indices_rcpp <- function(data, g, v = NULL, runs = 10L, seed = 123L) {
    .Call(`_BKP_get_twin_indices_rcpp`, data, g, v, runs, seed)
}

